//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PenShop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pen
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public byte[] Image { get; set; }
        public int TypeId { get; set; }
        public int ColorId { get; set; }
        public int ViewId { get; set; }
    
        public virtual PenColor PenColor { get; set; }
        public virtual PenType PenType { get; set; }
        public virtual PenView PenView { get; set; }
    }
}
